### ISSUE TITLE
Feature: Crear modal seleccionar cantidad

### ISSUE THREAD

**Issue by Mauri548** [RooftopAcademy/roofstore#118]
Al hacer click en el botón de seleccionar cantidad de un producto del carrito se debe abrir un modal como la siguiente vista:
- el fondo debe ser del color principal
- la cantidad seleccionada debe tener un borde izquierdo de color activo
- al clickear en la "X" o en el fondo se debe cerrar el modal
- el contenedor de cantidades debe ser scrolleable y permitir hasta 6 unidades y luego un botón para agregar mas de 6 unidades

![Captura](https://user-images.githubusercontent.com/51139854/144908466-58c954ae-78da-40ce-8faa-eda0e64f1f4a.PNG)

- al clickear en "más de 6 unidades" debe cambiar la vista por la siguiente:

![Captura3](https://user-images.githubusercontent.com/51139854/144908969-4b0dce05-7985-429e-9d2a-5a59c99ac980.PNG)

**Comment by Alonso-Pablo** [comment]
¿Esto en donde es?
Estuve viendo algún producto, le di a `Cantidad` y me saltó un modal diferente:
![Screenshot from 2021-12-13 10-25-32](https://user-images.githubusercontent.com/78811265/145820765-09d767f5-71b2-43fd-b5f8-fddd9c8a1e42.png)

**Comment by Mauri548** [comment]
Ese modal es en el carrito, cuando agregas algunos productos a tu carrito y queres modificar la cantidad
