### ISSUE TITLE
fix: Cambiar la url del link `Tiendas Oficiales` del Footer

### ISSUE THREAD

**Issue by Alonso-Pablo** [RooftopAcademy/roofstore#168]
## 🔧 Arreglar: 
- Cambiar la url del link `Tiendas Oficiales` que está en el Footer (de a `/officialStores` por `/stores`) 
![Screenshot from 2021-12-10 21-36-04](https://user-images.githubusercontent.com/78811265/145657067-0686830e-662c-4532-a6bf-323359f5f17a.png)

**Comment by alezvi** [comment]
@jocardozo esta tarea podes comenzarla.
