### ISSUE TITLE
feature: subir fotos o tomarlas desde la camara 

### ISSUE THREAD

**Issue by alezvi** [RooftopAcademy/roofstore#188]
- Al momento de publicar un producto el usuario puede subir imagenes desde la galeria o desde la camara
- La imagen es requerida
- Solo se aceptan formatos jpg, png, webp

**Comment by alezvi** [comment]
@feralba28 cual es el status actual de esta tarea ? Sigue en in progress hace 9 dias.

**Comment by feralba28** [comment]
Solo me faltan los test, para hoy estaría en condiciones de subirla.

> @feralba28 cual es el status actual de esta tarea ? Sigue en in progress hace 9 dias.
