### ISSUE TITLE
feature: implementar push notifications

### ISSUE THREAD

**Issue by alezvi** [RooftopAcademy/roofstore#189]

**Comment by alezvi** [comment]
@kevin-dev71 Cual es el status actual de esta tarea ? Hace 2 semanas sigue en in progress.

**Comment by kevin-dev71** [comment]
@alezvi actualmente está funcionando las notificaciones importando un service-worker que proporciona firebase, este service-worker se coloca en la carpeta public, exponiendo así las variables de entornos en el mismo archivo (no se puede inyectar con process.env en la carpeta public, a menos q modifiquemos el webpack).... espero que tengamos nuestro service-worker para adaptarlo
