### ISSUE TITLE
Team FPP - fix - Pablo Alonso

### ISSUE THREAD

**Issue by Alonso-Pablo** [RooftopAcademy/roofstore#215]
## Hacer una branch a partir de la rama `team-fernando-pablo-pablo` y trabajar las siguientes issues:

- [x] Cambiar el nombre de la carpeta `src/Pages/Public/DefensaConsumidor` de español a inglés.
- [x] Sacar el texto a una variable en el archivo: `src/Pages/Public/DefensaConsumidor/DefensaConsumidorBlock.js`
- [x] Sacar el texto a una variable en el archivo: `src/Pages/Public/DefensaConsumidor/DefensaConsumidorItem.js`
- [x] Sacar el texto a una variable o en un mock en el archivo: `src/Pages/Public/ProductPage/Block/BreadcrumbBlock.js`
- [x] Sacar el texto a un mock, el envío gratis vendría del backend: `src/Pages/Public/ProductPage/Block/FeaturedProductsBlock.js`
- [x] Sacar el texto a una variable en el archivo (los meses de garantía vienen del backend): `src/Pages/Public/ProductPage/Block/GarantiaBlock.js`
- [x] Sacar el texto a una variable en el archivo: `src/Pages/Public/ProductPage/Block/PaymentBlock.js`
- [x] Sacar el texto de las propiedades a una variable en el archivo: `src/Pages/Public/ProductPage/Block/ProductAction.js`
- [x]  Cambiar de español a ingles los paths del archivo: `src/App.js`

Cualquier mejoría adicional es bienvenida.

**Comment by kevin-dev71** [comment]
vos estais echando codigo tambien? @Alonso-Pablo  xD

**Comment by Alonso-Pablo** [comment]
> vos estais echando codigo tambien? @Alonso-Pablo xD

Claro que sí. Malabareando con frontend y backend
