### ISSUE TITLE
Quitar la clase txt-center por defecto del componente TextLine

### ISSUE THREAD

**Issue by FacundoAlba** [RooftopAcademy/roofstore#51]
La clase txt-center es necesaria solo en casos específicos, y ya que el componente <code>TextLine</code> admite el uso de clases por  <code>props</code> lo mejor seria removerla.

**Comment by Alonso-Pablo** [comment]
¿Alguna noticia de este issue?

**Comment by jocardozo** [comment]
No habíamos quedado en que se hacía cuando se termine de organizar lo de Rooftrap?

**Comment by alezvi** [comment]
@jocardozo @Alonso-Pablo  si esta tarea aun no la comenzaron deberia estar en "to-do"

**Comment by kevin-dev71** [comment]
cierro issue , ya tiene mucho tiempo, no se hará
