### ISSUE TITLE
Refactor Register Page

### ISSUE THREAD

**Issue by pablocanale** [RooftopAcademy/roofstore#56]
- [ ] Utilizar mejores practicas con el state para el cambio de display en los componentes.
- [x] Refactorizar el codigo repetido.

**Comment by kevin-dev71** [comment]
ya se pusheó la rama refactor-RegisterPage... queda pendiente:

- [ ] Utilizar mejores practicas con el state para el cambio de display en los componentes.
- [x] Refactorizar el codigo repetido.
