### ISSUE TITLE
Componente reutilizable para carga de datos

### ISSUE THREAD

**Issue by alezvi** [RooftopAcademy/roofstore#72]
- Ej https://media.discordapp.net/attachments/902175788785356830/913114308081229834/Screenshot_20211124-140549.jpg?width=525&height=1137
- Se muestra al ingresar a la ruta "/sell/itemTitle"
- Se muestra un texto indicativo del dato que debe ingresar el usuario
- Se muestra un input de una sola linea
- Abajo del input un texto de ayuda
- En el pie de pagina el boton continuar
- En boton permanece deshabilitado mientras el input no sea valido
- Una vez validado correctamente se puede clickear
- Al clickear debe redirigir a la siguiente pagina "/"

**Comment by Alonso-Pablo** [comment]
¿Esto es un issue para crear un componente o una página?
La ruta donde se va a mostrar este componente/página ¿no sería mejor `/sell/item-title` en vez de `/sell/itemTitle`?
